// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6kwdLiXDWBu0dwZiw9IUfroN2UxlrEg',
    appId: '1:34251951178:web:619773964d2520e508aab3',
    messagingSenderId: '34251951178',
    projectId: 'basedados-wip',
    authDomain: 'basedados-wip.firebaseapp.com',
    storageBucket: 'basedados-wip.appspot.com',
    measurementId: 'G-4ZZ0XEFF4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6ld4oJ7nVAOtrRfshWnPfmdXGtVNTyc',
    appId: '1:34251951178:android:7897e008d7e60aee08aab3',
    messagingSenderId: '34251951178',
    projectId: 'basedados-wip',
    storageBucket: 'basedados-wip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL7VYm1gVBAA2zye1tx6d6SIDH4NSpU-c',
    appId: '1:34251951178:ios:fef762550d4d1e2708aab3',
    messagingSenderId: '34251951178',
    projectId: 'basedados-wip',
    storageBucket: 'basedados-wip.appspot.com',
    iosBundleId: 'com.example.wip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL7VYm1gVBAA2zye1tx6d6SIDH4NSpU-c',
    appId: '1:34251951178:ios:65be7ee3150c5c6f08aab3',
    messagingSenderId: '34251951178',
    projectId: 'basedados-wip',
    storageBucket: 'basedados-wip.appspot.com',
    iosBundleId: 'com.example.wip.RunnerTests',
  );
}
